In [11]:
import numpy as np

import sys
module_path = '/home/diplomski-rad/consensus-net/src/python/dataset/'
if module_path not in sys.path:
    print('Adding dataset module.')
    sys.path.append(module_path)

import dataset

Adding dataset module.


## Create dataset with neighbourhood

In [2]:
X_paths = ['/home/diplomski-rad/blade/pb/pileups/e-coli-NCTC86/pileups-X-ref-indels.npy',
           '/home/diplomski-rad/blade/pb/pileups/m-morgani-NCTC235/pileups-X-ref-indels.npy',
           '/home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC92/pileups-X-ref-indels.npy',
           '/home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC129/pileups-X-ref-indels.npy']
y_paths = ['/home/diplomski-rad/blade/pb/pileups/e-coli-NCTC86/pileups-y-ref.npy',
           '/home/diplomski-rad/blade/pb/pileups/m-morgani-NCTC235/pileups-y-ref.npy',
           '/home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC92/pileups-y-ref.npy',
           '/home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC129/pileups-y-ref.npy']
neighbourhood_size = 10

X, y = dataset.create_dataset_with_neighbourhood(X_paths, y_paths, neighbourhood_size)

Parsing  /home/diplomski-rad/blade/pb/pileups/e-coli-NCTC86/pileups-X-ref-indels.npy  and  /home/diplomski-rad/blade/pb/pileups/e-coli-NCTC86/pileups-y-ref.npy


  0% (3551 of 4641652) |                 | Elapsed Time: 0:00:00 ETA:   0:04:21

Creating dataset with neighbourhood ...


100% (4641652 of 4641652) |##############| Elapsed Time: 0:04:14 Time:  0:04:14


Parsing  /home/diplomski-rad/blade/pb/pileups/m-morgani-NCTC235/pileups-X-ref-indels.npy  and  /home/diplomski-rad/blade/pb/pileups/m-morgani-NCTC235/pileups-y-ref.npy


  0% (1927 of 3799539) |                 | Elapsed Time: 0:00:00 ETA:   0:03:17

Creating dataset with neighbourhood ...


100% (3799539 of 3799539) |##############| Elapsed Time: 0:03:20 Time:  0:03:20


Parsing  /home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC92/pileups-X-ref-indels.npy  and  /home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC92/pileups-y-ref.npy


  0% (3680 of 4809037) |                 | Elapsed Time: 0:00:00 ETA:   0:04:21

Creating dataset with neighbourhood ...


100% (4809037 of 4809037) |##############| Elapsed Time: 0:04:08 Time:  0:04:08


Parsing  /home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC129/pileups-X-ref-indels.npy  and  /home/diplomski-rad/blade/pb/pileups/s-enterica-NCTC129/pileups-y-ref.npy


  0% (3647 of 4809037) |                 | Elapsed Time: 0:00:00 ETA:   0:04:24

Creating dataset with neighbourhood ...


100% (4809037 of 4809037) |##############| Elapsed Time: 0:04:09 Time:  0:04:09


In [3]:
np.save('./dataset-all-n10-X-indels', X)
np.save('./dataset-all-n10-y-indels', y)

## Reshape for convolutional nets

In [ ]:
X, y, X_train, X_validate, y_train, y_validate = dataset.read_dataset_and_reshape_for_conv(
    './dataset-all-n10-X-indels.npy', './dataset-all-n10-y-indels.npy', 0.1)

N/A% (0 of 16953527) |                   | Elapsed Time: 0:00:00 ETA:  --:--:--

X shape before reshaping: (16953527, 21, 6)
y shape before reshaping: (16953527, 4)


100% (16953527 of 16953527) |############| Elapsed Time: 0:17:04 Time:  0:17:04


X shape after reshaping: (16953527, 21, 1, 6)
y shape after reshaping: (16953527, 4)
Splitting to train and validation set.


In [ ]:
np.save('./dataset-n10-X-reshaped', X)
np.save('./dataset-n10-y-reshaped', y)
np.save('./dataset-n10-X-reshaped-train', X_train)
np.save('./dataset-n10-X-reshaped-validate', X_validate)
np.save('./dataset-n10-y-reshaped-train', y_train)
np.save('./dataset-n10-y-reshaped-validate', y_validate)

In [2]:
X, y = dataset.read_dataset_and_reshape_for_conv('./dataset-all-n10-X-indels.npy', './dataset-all-n10-y-indels.npy')
np.save('./dataset-n10-X-reshaped', X)
np.save('./dataset-n10-y-reshaped', y)

  0% (1943 of 16953527) |                | Elapsed Time: 0:00:00 ETA:   0:14:38

X shape before reshaping: (16953527, 21, 6)
y shape before reshaping: (16953527, 4)


100% (16953527 of 16953527) |############| Elapsed Time: 0:13:53 Time:  0:13:53


X shape after reshaping: (16953527, 21, 1, 6)
y shape after reshaping: (16953527, 4)


In [3]:
X.shape

(16953527, 21, 1, 6)

In [5]:
train_count = int(0.1 * X.shape[0])
print(train_count)

1695352


In [ ]:
shuffle_indices = np.arange(X.shape[0])
np.random.shuffle(shuffle_indices)

X_new = X[shuffle_indices]
y_new = y[shuffle_indices]

In [9]:
X_train = X[train_count:]
print(X_train.shape)
y_train = y[train_count:]
print(y_train.shape)

X_validate = X[:train_count]
y_validate = y[:train_count]
print(X_validate.shape)
print(y_validate.shape)

(15258175, 21, 1, 6)
(15258175, 4)
(1695352, 21, 1, 6)
(1695352, 4)


In [66]:
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.array([[1, 1], [2, 2], [3, 3]])


indices = np.arange(a.shape[0])
np.random.shuffle(indices)
print(indices)

a = a[indices]
b = b[indices]
print(a)
print(b)

[1 2 0]
[[2 2]
 [3 3]
 [1 1]]
[[2 2]
 [3 3]
 [1 1]]


In [7]:
from keras.utils import to_categorical

In [12]:
np.save('./tmp', np.arange(15001001))

In [14]:
X, y = np.load('./dataset-n10-X-reshaped.npy'), np.load('./dataset-n10-X-reshaped.npy')

In [18]:
import progressbar

with progressbar.ProgressBar(max_value=X.shape[0]) as progress_bar:
    for i, xi in enumerate(X):
        progress_bar.update(i)
        np.save('./X/{}'.format(i), xi)

100% (16953527 of 16953527) |############| Elapsed Time: 0:01:41 Time:  0:01:41


KeyboardInterrupt: 

In [3]:
import numpy as np

y = np.load('./dataset-n10-y-reshaped.npy')

y = np.argmax(y, axis=1)
print(y.shape)
np.save('./dataset-classes-y', y)

(16953527,)
