In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, BatchNormalization, Input
from keras.layers import Conv1D, MaxPooling1D, Conv2D
from keras.utils import np_utils
from keras.datasets import mnist

/home/ajuric/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
X, y = np.load('pysam-dataset-n3-X.npy'), np.load('pysam-dataset-n3-y.npy')

In [3]:
print(X.shape)
print(y.shape)

(3573946, 7, 4)
(3573946, 4)


In [4]:
import matplotlib.image
image = matplotlib.image.imread('image.jpg')
print(type(image))
print(image.shape)
print(image[0][0])
print(image[0].shape)

<class 'numpy.ndarray'>
(270, 480, 3)
[126 116 114]
(480, 3)


In [5]:
x1 = X[0]
print(x1)

[[ 0. 46.  0.  0.]
 [48.  0.  0.  0.]
 [ 0.  0.  0. 55.]
 [ 0.  0. 61.  0.]
 [ 0.  1. 61.  1.]
 [ 0. 63.  0.  0.]
 [ 0.  0. 66.  0.]]


In [6]:
new_x1 = np.dstack((x1[:, 0].reshape(7, 1), x1[:, 1].reshape(7, 1), x1[:, 2].reshape(7, 1), x1[:, 3].reshape(7, 1)))
print(new_x1.shape)
print(new_x1)
print(new_x1[0][0])

(7, 1, 4)
[[[ 0. 46.  0.  0.]]

 [[48.  0.  0.  0.]]

 [[ 0.  0.  0. 55.]]

 [[ 0.  0. 61.  0.]]

 [[ 0.  1. 61.  1.]]

 [[ 0. 63.  0.  0.]]

 [[ 0.  0. 66.  0.]]]
[ 0. 46.  0.  0.]


In [7]:
new_X = list()
for xi in X:
    new_xi = np.dstack((xi[:, 0].reshape(7, 1), xi[:, 1].reshape(7, 1), xi[:, 2].reshape(7, 1), xi[:, 3].reshape(7, 1)))
    new_X.append(new_xi)

new_X = np.array(new_X)
print(new_X.shape)

(3573946, 7, 1, 4)


In [8]:
X = new_X

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_validate, y_train, y_validate = train_test_split(X, y, test_size=0.10)
print(X_train.shape, X_validate.shape, y_train.shape, y_validate.shape)

(3216551, 7, 1, 4) (357395, 7, 1, 4) (3216551, 4) (357395, 4)


In [12]:
model = Sequential()
model.add(Flatten(input_shape=(7, 1, 4)))
model.add(Dense(40, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(4, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

batch_size = 10000
epochs = 3

# model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(X_validate, y_validate))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 28)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 40)                1160      
_________________________________________________________________
dropout_2 (Dropout)          (None, 40)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 164       
Total params: 1,324
Trainable params: 1,324
Non-trainable params: 0
_________________________________________________________________


In [10]:
from keras.models import Model

In [11]:
input_layer = Input(shape=(7, 1, 4))
conv_1 = Conv2D(filters=4, kernel_size=3, padding='same', activation='relu')(input_layer)
# pool_1 = MaxPooling1D(pool_size=1)(conv_1)

flatten = Flatten()(conv_1)
predictions = Dense(4, activation='softmax')(flatten)

# model.add(Conv1D(filters=5, kernel_size=3, padding='same', activation='relu', input_shape=(7, 1)))
# model.add(MaxPooling1D())
# # model.add(Dense(40, activation='relu'))
# # model.add(BatchNormalization())
# # model.add(Dense(40, activation='relu'))

# # model.add(Dropout(0.25))
# model.add(Dense(4, activation='softmax'))

model = Model(input_layer, predictions)

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print(model.summary())

batch_size = 10000
epochs = 200

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(X_validate, y_validate))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 7, 1, 4)           0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 7, 1, 4)           148       
_________________________________________________________________
flatten_1 (Flatten)          (None, 28)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 116       
Total params: 264
Trainable params: 264
Non-trainable params: 0
_________________________________________________________________
None
Train on 3216551 samples, validate on 357395 samples
Epoch 1/200
3216551/3216551 [==============================] - 5s 1us/step - loss: 4.3247 - acc: 0.6805 - val_loss: 0.1373 - val_acc: 0.9866
Epoch 2/200
3216551/3216551 [==============================] - 3s 1us/step - 

3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0341 - acc: 0.9914 - val_loss: 0.0346 - val_acc: 0.9911
Epoch 53/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0340 - acc: 0.9914 - val_loss: 0.0349 - val_acc: 0.9911
Epoch 54/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0340 - acc: 0.9914 - val_loss: 0.0350 - val_acc: 0.9911
Epoch 55/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0340 - acc: 0.9914 - val_loss: 0.0346 - val_acc: 0.9911
Epoch 56/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0339 - acc: 0.9914 - val_loss: 0.0350 - val_acc: 0.9908
Epoch 57/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0340 - acc: 0.9914 - val_loss: 0.0349 - val_acc: 0.9910
Epoch 58/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0340 - acc: 0.9914 - val_loss: 0.0349 - val_acc: 0.9911
Epoch 59/200
321655

Epoch 110/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0346 - val_acc: 0.9911
Epoch 111/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0344 - val_acc: 0.9912
Epoch 112/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0346 - val_acc: 0.9911
Epoch 113/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0336 - acc: 0.9915 - val_loss: 0.0346 - val_acc: 0.9912
Epoch 114/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0353 - val_acc: 0.9909
Epoch 115/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0345 - val_acc: 0.9911
Epoch 116/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0337 - acc: 0.9915 - val_loss: 0.0343 - val_acc: 0.9911

3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0332 - acc: 0.9915 - val_loss: 0.0339 - val_acc: 0.9912
Epoch 168/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0332 - acc: 0.9915 - val_loss: 0.0338 - val_acc: 0.9913
Epoch 169/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0332 - acc: 0.9915 - val_loss: 0.0337 - val_acc: 0.9912
Epoch 170/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0331 - acc: 0.9915 - val_loss: 0.0338 - val_acc: 0.9912
Epoch 171/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0331 - acc: 0.9915 - val_loss: 0.0338 - val_acc: 0.9912
Epoch 172/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0331 - acc: 0.9915 - val_loss: 0.0338 - val_acc: 0.9913
Epoch 173/200
3216551/3216551 [==============================] - 3s 1us/step - loss: 0.0331 - acc: 0.9915 - val_loss: 0.0342 - val_acc: 0.9912
Epoch 174/200

In [12]:
model.save('./CNet-conv_2d_N3.h5')

In [15]:
model = Sequential()
model.add(Flatten(input_shape=(7, 4)))
model.add(Dense(20, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(4, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

batch_size = 100000
epochs = 3

model.fit(X_train, y_train, batch_size=10, epochs=epochs, validation_data=(X_validate, y_validate))

Train on 3216551 samples, validate on 357395 samples
Epoch 1/3
3216551/3216551 [==============================] - 1035s 322us/step - loss: 0.0725 - acc: 0.9781 - val_loss: 0.0266 - val_acc: 0.9912
Epoch 2/3
3216551/3216551 [==============================] - 1010s 314us/step - loss: 0.0547 - acc: 0.9812 - val_loss: 0.0253 - val_acc: 0.9908
Epoch 3/3
3216551/3216551 [==============================] - 1014s 315us/step - loss: 0.0538 - acc: 0.9813 - val_loss: 0.0254 - val_acc: 0.9912


In [16]:
model.save('./CNet-L20-BN-L10-N3')

In [ ]:
model = Sequential()
model.add(Flatten(input_shape=(7, 4)))
model.add(Dense(20, activation='relu'))
model.add(BatchNormalization())
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(4, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

batch_size = 100000
epochs = 3

model.fit(X_train, y_train, batch_size=10, epochs=epochs, validation_data=(X_validate, y_validate))
model.save('./CNet-L20-BN-L10-N3')